Repository kasp470f/1semester, pull requests merged in 2021-01, with the labels that each got.

#5 Kasper
  .gitignore
  Applikationen/.vs/1SemestersProjekt/v16/.suo
  Applikationen/obj/Debug/.NETFramework,Version=v4.7.2.AssemblyAttributes.cs
  Applikationen/obj/Debug/1SemestersProjekt.csprojAssemblyReference.cache
  Applikationen/obj/Debug/1SemestersProjekt_MarkupCompile.cache
  Applikationen/obj/Debug/1SemestersProjekt_MarkupCompile.i.cache
  Applikationen/obj/Debug/1SemestersProjekt_MarkupCompile.i.lref
  Applikationen/obj/Debug/1SemestersProjekt_MarkupCompile.lref
  Applikationen/obj/Debug/App.g.cs
  Applikationen/obj/Debug/App.g.i.cs
  Applikationen/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
  Applikationen/obj/Debug/MainWindow.g.cs
  Applikationen/obj/Debug/MainWindow.g.i.cs
Labels: needTeacher

#20 Create DatabaseSetupFinal.sql
  Dokumentation/SQL - DDL - DML/DatabaseSetupFinal.sql
Labels: programming

#24 Added new DMLs and changed DDL files
  Dokumentation/SQL - DDL - DML/DatabaseSetupFinal-DDL.sql
  Dokumentation/SQL - DDL - DML/InsertIndustries-DML.sql
  Dokumentation/SQL - DDL - DML/InsertMunicipalities-DML.sql
Labels: programming

#28 Update Dokumentation Readme med SQL
  Dokumentation/README.md
Labels: documentation

#31 Changes to DML files
  Dokumentation/SQL - DDL - DML/DatabaseSetupFinal-DDL.sql
  Dokumentation/SQL - DDL - DML/InsertIndustries-DML.sql
  Dokumentation/SQL - DDL - DML/InsertMunicipalities-DML.sql
Labels: programming

#36 First Xaml design for restrictions page
  Applikationen/Applikationen.csproj
  Applikationen/Assets/Images/OkIcon.png
  Applikationen/Assets/Images/WarningIcon.png
  Applikationen/MainWindow.xaml
  Applikationen/MainWindow.xaml.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/RestrictionsPage.xaml
  Applikationen/Views/Partials/Toolbar.xaml
  Dokumentation/SQL - DDL - DML/DatabaseSetupFinal - DDL.sql
Labels: programming

#35 New ERD diagram
  Dokumentation/Modeller/ERD.png
  Dokumentation/Modeller/ERD_v3.png
Labels: documentation

#38 Front page added with code for style in app.xaml
  Applikationen/App.xaml
  Applikationen/Applikationen.csproj
  Applikationen/Views/Pages/FrontPage.xaml
Labels: programming

#47 DML and DDL updated to fit new database names
  Dokumentation/SQL - DDL - DML/DatabaseSetupFinal-DDL.sql
  Dokumentation/SQL - DDL - DML/InsertIndustries-DML.sql
  Dokumentation/SQL - DDL - DML/InsertMunicipalities-DML.sql
Labels: database

#49 Samlet style
  Applikationen/App.xaml
  Applikationen/MainWindow.xaml
  Applikationen/MainWindow.xaml.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/RestrictionsPage.xaml
Labels: programming

#50 Added Restrictions DML
  Dokumentation/SQL - DDL - DML/InsertMunicipalities-DML.sql
  Dokumentation/SQL - DDL - DML/InsertRestrictions-DML.sql
Labels: database

#53 Created functionality to show CSV data on front page
  Applikationen/CoronaData/CoronaData.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/FrontPage.xaml.cs
Labels: programming

#58 opdatering log 11/1
  Dokumentation/DailyLog.md
Labels: documentation

#59 Updated Ok Icon
  Applikationen/Assets/Images/OkIcon.png
Labels: programming

#60 Daily Merge of Develop Branch to Main
  .gitignore
  Applikationen/App.xaml
  Applikationen/Assets/Images/OkIcon.png
  Applikationen/CoronaData/CoronaData.cs
  Applikationen/MainWindow.xaml
  Applikationen/MainWindow.xaml.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/FrontPage.xaml.cs
  Applikationen/Views/Pages/RestrictionsPage.xaml
  Dokumentation/DailyLog.md
  Dokumentation/SQL - DDL - DML/DatabaseSetupFinal-DDL.sql
  Dokumentation/SQL - DDL - DML/InsertIndustries-DML.sql
  Dokumentation/SQL - DDL - DML/InsertMunicipalities-DML.sql
  Dokumentation/SQL - DDL - DML/InsertRestrictions-DML.sql
Labels: database, documentation, programming

#65 Pushing Indikator, CSV Reader, og folder path picker til Develop branch
  Applikationen/App.xaml
  Applikationen/Applikationen.csproj
  Applikationen/CoronaData/CoronaData.cs
  Applikationen/CoronaData/RegionData.cs
  Applikationen/CoronaData/municipalityPositive.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/FrontPage.xaml.cs
Labels: programming

#67 Municipality.cs code
  Applikationen/Applikationen.csproj
  Applikationen/DatabaseClasses/Municipality.cs
Labels: programming

#68 Municipality data binding and csv reading
  Applikationen/Applikationen.csproj
  Applikationen/Assets/Images/Readme.md
  Applikationen/Assets/Images/covid-19.ico
  Applikationen/CoronaData/municipalityPositive.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/FrontPage.xaml.cs
  Applikationen/covid-19.ico
Labels: documentation, programming

#72 Kasper
  Applikationen/ClassDiagram/ClassDiagram.cd
  Applikationen/CoronaData/municipalityPositive.cs
  Applikationen/DatabaseClasses/Industry.cs
  Applikationen/DatabaseClasses/Municipality.cs
  Applikationen/DatabaseClasses/Restriction.cs
  Applikationen/Views/Pages/FrontPage.xaml.cs
  Dokumentation/DailyLog.md
Labels: database, programming

#74 Merge to develop
  Applikationen/DatabaseClasses/Municipality.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/FrontPage.xaml.cs
  Applikationen/Views/Pages/RestrictionsPage.xaml
  Applikationen/Views/Pages/RestrictionsPage.xaml.cs
  Dokumentation/SQL - DDL - DML/InsertMunicipalities-DML.sql
Labels: documentation, programming

#75 Merge to main
  Applikationen/App.xaml
  Applikationen/Applikationen.csproj
  Applikationen/Assets/Images/Readme.md
  Applikationen/Assets/Images/covid-19.ico
  Applikationen/ClassDiagram/ClassDiagram.cd
  Applikationen/CoronaData/CoronaData.cs
  Applikationen/CoronaData/RegionData.cs
  Applikationen/CoronaData/municipalityPositive.cs
  Applikationen/DatabaseClasses/Industry.cs
  Applikationen/DatabaseClasses/Municipality.cs
  Applikationen/DatabaseClasses/Restriction.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/FrontPage.xaml.cs
  Applikationen/Views/Pages/RestrictionsPage.xaml
  Applikationen/Views/Pages/RestrictionsPage.xaml.cs
  Applikationen/covid-19.ico
  Dokumentation/DailyLog.md
  Dokumentation/SQL - DDL - DML/InsertMunicipalities-DML.sql
Labels: database, documentation, programming

#85 Opdatering af log og funktionalitet for visning af industry restrictions i data grids
  Applikationen/DatabaseClasses/IndustryRestriction.cs
  Applikationen/DatabaseClasses/Municipality.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/FrontPage.xaml.cs
  Applikationen/Views/Pages/RestrictionsPage.xaml.cs
  Dokumentation/DailyLog.md
Labels: programming

#97 Fixede delete funktion og display af industriesrestrictions og mulighed for at tilføje og slette restriktioner påført til industrierne. Fik også lavet indikator logik og styling, og mere.
  Applikationen/App.xaml
  Applikationen/CoronaData/municipalityPositive.cs
  Applikationen/DatabaseClasses/Industry.cs
  Applikationen/DatabaseClasses/IndustryRestriction.cs
  Applikationen/DatabaseClasses/Municipality.cs
  Applikationen/DatabaseClasses/Restriction.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/FrontPage.xaml.cs
  Applikationen/Views/Pages/RestrictionsPage.xaml
  Applikationen/Views/Pages/RestrictionsPage.xaml.cs
  Dokumentation/Modeller/Klassediagram.PNG
  Dokumentation/SQL - DDL - DML/InsertIndustries-DML.sql
Labels: database, documentation, programming

#107 Vores sidste pull request til develop
  Applikationen/CoronaData/RegionData.cs
  Applikationen/CoronaData/municipalityPositive.cs
  Applikationen/DatabaseClasses/Industry.cs
  Applikationen/DatabaseClasses/IndustryRestriction.cs
  Applikationen/DatabaseClasses/Municipality.cs
  Applikationen/DatabaseClasses/Restriction.cs
  Applikationen/ViewModels/Commands/SetPageContentCommand.cs
  Applikationen/ViewModels/MainWindowViewModel.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/FrontPage.xaml.cs
  Applikationen/Views/Pages/RestrictionsPage.xaml
  Applikationen/Views/Pages/RestrictionsPage.xaml.cs
  Dokumentation/DailyLog.md
  Dokumentation/Modeller/Domænemodel.png
  Dokumentation/Modeller/Sekvensdiagrammer.png
  Dokumentation/Use Cases/UC-1.1V2.docx
Labels: database, documentation, programming

#110 The final product
  Applikationen/App.xaml
  Applikationen/CoronaData/RegionData.cs
  Applikationen/CoronaData/municipalityPositive.cs
  Applikationen/DatabaseClasses/Industry.cs
  Applikationen/DatabaseClasses/IndustryRestriction.cs
  Applikationen/DatabaseClasses/Municipality.cs
  Applikationen/DatabaseClasses/Restriction.cs
  Applikationen/ViewModels/Commands/SetPageContentCommand.cs
  Applikationen/ViewModels/MainWindowViewModel.cs
  Applikationen/Views/Pages/FrontPage.xaml
  Applikationen/Views/Pages/FrontPage.xaml.cs
  Applikationen/Views/Pages/RestrictionsPage.xaml
  Applikationen/Views/Pages/RestrictionsPage.xaml.cs
  Dokumentation/DailyLog.md
  Dokumentation/Modeller/Domænemodel.png
  Dokumentation/Modeller/Klassediagram.PNG
  Dokumentation/Modeller/Sekvensdiagrammer.png
  Dokumentation/SQL - DDL - DML/DatabaseSetupFinal-DDL.sql
  Dokumentation/SQL - DDL - DML/InsertIndustries-DML.sql
  Dokumentation/SQL - DDL - DML/InsertMunicipalities-DML.sql
  Dokumentation/Use Cases/UC-1.1V2.docx
Labels: database, documentation, programming
